language: objective-c
osx_image: xcode8.3
install: echo
before_install:
  - gem install xcpretty
  - mkdir -p ~/Library/Logs/DiagnosticReports
script:
  - set -o pipefail
  - scripts/bootstrap.sh
  - NSUnbufferedIO=YES xcodebuild -scheme pxctest test | xcpretty -c
  - brew tap plu/pxctest && brew install pxctest --HEAD && pxctest version
