language: objective-c
osx_image: xcode8.1
install: echo
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - scripts/bootstrap.sh
  - NSUnbufferedIO=YES xcodebuild -scheme pxctest test | xcpretty -c
